source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'client-mpp-ios' do
  # your other pod
  # ...
  pod 'Kingfisher', '~> 5.0'
  pod 'SwiftKeychainWrapper'
end
